# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
# example: https://github.com/travis-ci-examples/php
language: php

php:
  # aliased to a recent 7.x version
  - '7.0'
  # aliased to a recent 7.1.x version
  - '7.1'
  # aliased to a recent 7.2.x version
  - '7.2'
  # aliased to a recent hhvm version
  # - hhvm # This package requires php >=7.0.0 but your HHVM version does not satisfy that requirement.
  - nightly

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
#  - DB=pgsql
  - DB=sqlite

matrix:
  fast_finish: true # Will finish as soon as a job has failed, or when the only jobs left allow failures.
#  exclude:
#    - php: hhvm
#      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  include:
    - php: '7.0'
      env: 'DB=mysql COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
#  allow_failures:
#    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS test_laravel_model_base;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database test_laravel_model_base;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test_laravel_model_base;" -uroot; fi
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - vendor/bin/phpcs --standard=phpcs.xml
  - vendor/bin/phpunit --configuration phpunit_$DB.xml --coverage-text
