# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
# example: https://github.com/travis-ci-examples/php
language: php

php:
  - '8.0'
  - '8.1'

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

#os:
#  - linux
#  #- osx     # PHP not working
#  #- windows # PHP not supported

services:
  - mysql

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
#  - DB=pgsql
  - DB=sqlite

matrix:
  fast_finish: true # Will finish as soon as a job has failed, or when the only jobs left allow failures.

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS test_laravel_model_base;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database test_laravel_model_base;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test_laravel_model_base;" -uroot; fi
  - travis_retry composer install ${COMPOSER_FLAGS} --no-ansi --no-interaction --no-progress --no-suggest --no-scripts --prefer-dist

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - ./vendor/bin/phpcs --standard=phpcs.xml
  - ./vendor/bin/phpcs --config-set installed_paths ./vendor/phpcompatibility/php-compatibility && ./vendor/bin/phpcs --standard=phpcs-php-compatibility.xml
  - ./vendor/bin/phpstan analyse -c phpstan.ci.neon --no-progress
  - ./vendor/bin/phpunit --configuration phpunit_$DB.xml --coverage-text
