# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
# example: https://github.com/travis-ci-examples/php
language: php

php:
  # aliased to the lowest 5.5.x version
  - '5.5'
  # aliased to a recent 5.6.x version
  - '5.6'
  # aliased to a recent 7.x version
  - '7.0'
  # aliased to a recent 7.1.x version
  - '7.1'
  # aliased to a recent hhvm version
  - hhvm
  - nightly

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  - DB=pgsql

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  include:
    - php: '5.5'
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
  allow_failures:
    - php: 7.0
    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS laravel_model_base_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database laravel_model_base_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS laravel_model_base_test;" -uroot; fi
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --configuration phpunit_$DB.xml --coverage-text